baseURL = "https://ca-software.github.io/"
languageCode = "en-gb"
title = "Clifford Agius | CA-Software Ltd"
theme = "hugo-theme-cleanwhite"


# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-158344868-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/Banner.png"
  SEOTitle = ""
  description = "Blogging about being a Pilot flying a B787 around the world as well as being a .NET developer in the Xamarin/C#/IOT space. Have a question about any of that send them over I will try my best..."
  keyword = "Freelance .NET IoT Developer c# Azure CASOftware"
  slogan = "Freelance .NET / IoT Developer that just so happens to fly a Boeing 787 around the world."

  image_404 = "img/404-bg.jpg"
  title_404 = "Oh No... Master Warning... :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Freelance Software Developer in the Dotnet and IOT space, International Speaker and when not doing all that I am a Boeing 787 Pilot for a Major UK Airline. I'm here Blogging about flying the B787 around the world as well as being a .NET developer in the Xamarin/C#/IOT space. Have a question about any of that send them over I will try my best..."
  #sidebar_avatar = "/img/ProfilePic.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "/img/ProfilePic.JPG"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  #ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  #reward = true 
  # reward_guide = "" 

  friends = false
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "CliffordAgius@CA_Software.co.uk"
#  facebook      = "full profile url in facebook"
#  googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/CliffordAgius"
  #Company LinkedIn
  #linkedin       = "https://www.linkedin.com/in/clifford-agius-2a8b44176/"  
  #Personal LinkedIn
  linkedin       = "https://www.linkedin.com/in/clifford-agius/"  
#  stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
# instagram     = "full profile url in instagram"
  github         = "https://github.com/CliffAgius"
#  wechat         = "your wechat qr code image"
#  medium         = "full profile url in medium"
#  #pinterest     = "full profile url in pinterest"
#  #reddit        = "full profile url in reddit"
#  #gitlab        = "full profile url in gitlab"
#  #mastodon      = "full profile url in mastodon"
#  #keybase       = "full profile url in keybase"
#  #xing          = "https://www.xing.com/profile/yourxingid"
#  #git           = "full profile url for git user"
  

  
  [[params.addtional_menus]]
  title =  "Speaking"
  href =  "/top/speaking/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"
  [[params.addtional_menus]]
  title =  "Flying"
  href =  "/top/flying/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
